### ISSUE TITLE
container is exiting 

### ISSUE THREAD

**Issue by publicocean0** [szyhf/DIDockerfiles#1]
96543bc1b7e9        szyhf:gitolite             "/bin/bash"              7 minutes ago       Exited (0) 4 seconds ago                              gitolite

**Comment by szyhf** [comment]
Oh, sorry to hear that

**Comment by szyhf** [comment]
@publicocean0 recommend you to use `gogs` or `gitea` instead

**Comment by publicocean0** [comment]
thanks for suggestion i didnt kow them :)  I gave a look ... very nice app. Just maybe problem there is no way for limiting permission on branch for collaborators like in gitolite (branch tree for example)

**Comment by szyhf** [comment]
of course not, gitolite is just a simple application provide base control and those are face to more complex usage.

**Comment by publicocean0** [comment]
i added a issue new feature in gitea for adding fine grane permittions like in gitolite

**Comment by szyhf** [comment]
I don‘t think there are any feature  which `gitolite` can provide but `gitea` or `gogs` can't……

**Comment by szyhf** [comment]
What I want to say is just give up `gitolite` and use `gitea` or `gogs` instead...

**Comment by publicocean0** [comment]
both for me it seams the opposite. gitea is a great gui. But gitolite is more powerfull with permissions.
in gitea you can just add collaborators. But in gitolite you can filter permittions per teams, per developer , per branch , per regular expression in a path,.... Maybe in gitolite regular expression is also too much ... but  gitea cant filter  per subtree and branch. For this i added a issue. Team is discussing.

**Comment by szyhf** [comment]
Oh~
