### ISSUE TITLE
Question about ServerName?

### ISSUE THREAD

**Issue by odunybrad** [szyhf/DIDockerfiles#2]
Thanks for providing the container! 
I am doing a research aiming at finding issues in configuration files. After pulling the image we notice that `ServerName` is set to `dummy-host.example.com` in `zyhf_httpd-alpine/usr/local/apache2/conf/original/extra/httpd-vhosts.conf` and not changed in any other config files.  

However, the HttpD [official document](https://httpd.apache.org/docs/2.4/mod/core.html#servername) recommends to set `ServerName` to identify yourself. "For optimal reliability and predictability, you should specify an explicit hostname and port using the ServerName directive."

Could you please provide a knob to specify the value of ServerName?

**Comment by szyhf** [comment]
The directory of `conf` is design to be a volume and user can mount it to provider there're own configuration files. The file already exist is just for examples.
